services:
  backend:
    build: ./backend
    # command: gunicorn -w 1 -k uvicorn.workers.UvicornWorker --reload --bind 0.0.0.0:8000 --access-logfile - app.main:app
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/home/appuser:z
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    restart: unless-stopped
